name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install --no-save

      # Step 4: Run lint and tests (optional, can be customized)
      - name: Lint and Test
        run: |
          npm run lint || true
          npm test || true

      # Step 5: Configure Git user (required for version commit)
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Bump the version, commit the change, and push
      - name: Bump version, commit, and push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm version patch -m "Bump version to %s [skip ci]"
          git push --follow-tags

      # Step 7: Publish to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
